### ISSUE TITLE
Agent does not forward gateway id to sdk during device activation/update

### ISSUE THREAD

**Issue by oguzcankirmemis** [Open-IoT-Service-Platform/oisp-iot-agent#38]

**Comment by srware** [comment]
Can you give some more details on what problem this causes? Is it just that the agent and frontend go out of sync if the gateway id gets updated on the agent or something else?

**Comment by srware** [comment]
I think this got fixed right @oguzcankirmemis ?

**Comment by oguzcankirmemis** [comment]
Yeah, it did, closing...
